name: HW1-F Failing Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate Error
        run: |
          echo "Something went wrong ❌"
          exit 1
